### ISSUE TITLE
Please update the recipe for Angular CLI

### ISSUE THREAD

**Issue by raidenfreeman** [Microsoft/vscode-recipes#100]
As you can see in [this issue](https://github.com/angular/angular-cli/issues/9729), debugging is broken because of inconsistent sourcemap lines numbers.

The improvement proposed by @blopez2010 :
```
{
      "name": "ng serve",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceRoot}",
      "userDataDir": "${workspaceRoot}/.vscode/chrome",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:/./*": "${webRoot}/*",
        "webpack:/src/*": "${webRoot}/src/*",
        "webpack:/*": "*",
        "webpack:/./~/*": "${webRoot}/node_modules/*"
      }
}
```

did fix the issue for me.

I'm using Angular CLI v1.7.4, node v8.9.4, VS Code v1.22.2 .

**Comment by jabas06** [comment]
This is issue is still occurring with Angular CLI 6.0, even using the last update made on a39ee09.
 What worked for me was setting webRoot like this:
`
"webRoot": "${workspaceRoot}"
`

**Comment by auchenberg** [comment]
@jabas06 We'd appreciate a PR!
