### ISSUE TITLE
Jest debugging instructions no longer work

### ISSUE THREAD

**Issue by jordanblanchet** [Microsoft/vscode-recipes#107]
After the change earlier today to debugging-jest-tests/README.md, the launch.json configuration no longer works for me.

When I try to launch Jest Current File, I get this error message:

`Cannot launch program D:\git\myproject\node_modules\.bin\jest; setting the outFiles attribute might help.`

Jest and jest-cli are both installed (22.4.4). jest.cmd is in the \node_modules\.bin directory.

**Comment by auchenberg** [comment]
@jordanblanchet Please provide more information about your setup. Are you running windows? YourNode version, etc.

A demo project would be great too.

This sounds like a problem of windows vs linux

/k

**Comment by auchenberg** [comment]
Ping @fallanic

**Comment by fallanic** [comment]
I'm not so familiar with nide development on windows, but I do have a windows laptop at work, I'll have a look at it first thing in the morning.

**Comment by jordanblanchet** [comment]
Hello, here's some of my system information: 

 ` System:
    OS: Windows 10
    CPU: x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  Binaries:
    Node: 9.4.0 - C:\nodejs\node.EXE
    Yarn: 1.3.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\nodejs\npm.CMD`

I'm using VS Code 1.23.1

It happens in a very simple project. One test file, one package installed (jest 23.1.0). Jest runs fine via npm scripts. When I try to launch Jest Current File with the new launch config, it fails with the above message.

**Comment by fallanic** [comment]
Indeed I am able to reproduce on windows @jordanblanchet @auchenberg 

I am not exactly sure why this is happening, as running `./node_modules/.bin/jest` in a windows `command prompt` does work.

In a perfect world we want a launch config which always work independently of the OS type.
So we should find the reason why we're getting this error on windows.

In the meantime, we can't keep a configuration which doesn't work on windows, so I see several solutions (none of them are perfect) : 

- we roll back to the previous version of the launch config, and add a comment explaining the user might need to replace `"program": "${workspaceFolder}/node_modules/jest/bin/jest",` by `"program": "${workspaceFolder}/node_modules/jest-cli/bin/jest",` when there is no `node_modules/jest` folder in the project
- we use this configuration instead
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Jest All",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
                "--runInBand"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Jest Current File",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
                "${relativeFile}"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        }
    ]
}
```

This launch config will work for all users on MacOS / Linux independently of what jest package they installed (`jest` or `jest-cli`).

This will also work for all users on windows who installed the `jest` module.

This won't work for Windows users using `jest-cli` (i.e. `react-boilerplate` users), so we need to add the same comment explaining they might need to replace `"program": "${workspaceFolder}/node_modules/jest/bin/jest",` with` "program": "${workspaceFolder}/node_modules/jest-cli/bin/jest",`

Again there must be a better way to have a universal launch config, I'm not sure why `node_modules/.bin/jest` works in a command prompt but not in VS Code.

Thanks let me know.

**Comment by auchenberg** [comment]
@fallanic Thanks for the debugging! 

To clarify: The issue seems to be that `./node_modules/.bin/jest` don't work from the integrated terminal in VS Code, but works for Command Prompt on Windows?

One hypothesis could be that the integrated terminal is using `powershell` on windows. To validate this can you try removing `"console": "integratedTerminal",` from the debug configurations? This should launch jest outside of the integrated terminal.

**Comment by fallanic** [comment]
Great idea, I can try that when I'm back to my windows machine tomorrow 👍 

I somehow didn't pay attention to that option, could be the culprit.
Speaking of which, I'm not quite sure what this other option does

`"internalConsoleOptions": "neverOpen"`

It doesn't seem to be [documented here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes) even if it's present in an [example](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited). 
Not sure if that's necessary or not 🤔

**Comment by auchenberg** [comment]
@fallanic It means that we don't open the integrated terminal, but launch it in.

**Comment by LotfiMEZIANI** [comment]
Hello !

Sorry if this is note the correct place to post this issue.

I am debugging the unit tests of a React application. I had the same problem as @jordanblanchet.

I changed my configuration to this, as indicated by @fallanic :
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Jest All",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
                "--runInBand"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Jest Current File",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
                "${relativeFile}"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        }
    ]
}
`

Now the unit tests are running ... But I have a new error (which I do not have if I run the tests without debugging). all crash tests (they should not) and I have the following errors (I think it's related to Babel & JSX...) :
`
Test suite failed to run

    C:/L/git/ecmwebapp_frontend/src/scripts/components/DocsSearch/DocsSearch.test.js: Unexpected token (16:22)
        14 |     };
        15 |
      > 16 |     wrapper = shallow(<DocsSearch {...mockProps} />);
           |                       ^
        17 |   });
        18 |
        19 |   it("Should render without throwing an error", () => {
`

My config:
```
OS                 : Windows7 SP1
NPM              : 5.6.0
React             : "^16.3.1"
React-scripts : "1.1.4",
```

**Comment by fallanic** [comment]
@auchenberg should I go ahead and send a PR with solution number 2 from [my previous comment](https://github.com/Microsoft/vscode-recipes/issues/107#issuecomment-398448046)?

**Comment by auchenberg** [comment]
@fallanic Please do, and thanks!
