### ISSUE TITLE
Possible to apply same settings with Visual Studio Enterprise

### ISSUE THREAD

**Issue by MikaelUmaN** [Microsoft/vscode-recipes#109]
Hi. Sorry if this is not a good forum for asking this. In that case feel free to point me somewhere else.

Is it possible to use these kinds of launch configurations on "regular" visual studio? It seems visual code is generally more flexible in terms of embracing non-Microsoft tools and setting up your projects in a flexible way, as opposed to trying to understand Visual Studio xml project/build files.

What is Microsoft's recommended approach for us having Visual Studio Enterprise and still wanting to develop .NET Core apps, including SPAs with react+redux and jest unit testing?

Would I do well to install Visual Studio Code alongside the Enterprise edition and use them for different purposes?

**Comment by auchenberg** [comment]
Hi @MikaelUmaN To my knowledge we currently don't provide such recipes for VS. I have forwarded this to the team. Stay tuned.

**Comment by MikaelUmaN** [comment]
Having gotten a better understanding of VS Code vs VS Enterprise my conclusion is that VS Code is really the preferred editor to use for these types of projects. I'm satisifed with that and so am closing this issue.
