### ISSUE TITLE
Error shown on Debug Console after start debugging

### ISSUE THREAD

**Issue by lesliedoghouse** [Microsoft/vscode-recipes#111]
After start debugging mode, my Debug Console show the following error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! banhoh-mobile@ debug: `meteor run --inspect`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the banhoh-mobile@ debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leslie/.npm/_logs/2018-07-03T12_56_19_765Z-debug.log
```

Is this a critical error? How to fix? Please advice, thank you.

**Comment by auchenberg** [comment]
@lesliedoghouse Check your `/Users/leslie/.npm/_logs/2018-07-03T12_56_19_765Z-debug.log` for more details. Your meteor app fails starting when running `meteor run --inspect`. Try running this from your terminal in the workspace folder. Once that works VS Code debugging will work too.
