### ISSUE TITLE
Is this the expected behaviour? Meteor + VS Code + Chrome Debugger

### ISSUE THREAD

**Issue by lesliedoghouse** [Microsoft/vscode-recipes#112]
I got the debugger running with meteor app. But I feel the behaviour a bit odd.

Behaviours:

1. I have to close all Chrome instances running on my desktop.
2. When at breakpoint, make changes and save, meteor will rebuild and restart (takes some time)
3. Once save and meteor restarted, debugger no longer attached. I have to Stop and Start debugger again.

Is the above expected behaviour? If yes, then this integrated debugger is not very help and quite hassle to use.

Please correct me if I'm wrong. Thank you.

**Comment by mrslwiseman** [comment]
I've had exact same problem all week and I've been trying hard to get it going. I finally succeeded with server side debugging, havn't quite worked out server/client at same time, but Im happy.
Try this

1.  launch.json:
```{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "server",
            "restart": true,
            "port": 9229,
        },
    ],
}```

2. run meteor in its own terminal
`meteor run --inspect`

3. Start up vscode debugger.
Take note of 'debugger attached' output in meteors terminal

4. Open up browser localhost:3000 and go for it!

For client side as well:
5. Chrome devtools > Sources: Add your work directory, then add client breakpoints there.

Has worked flawlessly for me so far.
