### ISSUE TITLE
Cannot connect to runtime process, ECONNREFUSED

### ISSUE THREAD

**Issue by MikaelUmaN** [Microsoft/vscode-recipes#113]
Hello. I installed VS Code and am trying to run Jest tests from the create-react-app. I get this error, however:

Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:port)

where port is a random very high number (e.g. 28065)

I have tried the following configs:

```
    "configurations": [
        {
            "name": "Debug CRA Tests",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "${workspaceRoot}/node_modules/react-scripts/bin/react-scripts.js",
            "args": ["test", "--runInBand", "--no-cache", "--env=jsdom"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Jest All",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": ["--runInBand"],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
              "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            }
        },
```

The closest I have been able to get is to run:

`node --inspect-brk .\node_modules\react-scripts\bin\react-scripts.js test --runInBand --no-cache --env=jsdom`

from a terminal and attach from vs code using:

```
        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229
        },
```

This seems to attach fine, but breakpoints in tests stay gray and "unverified, set but not yet bound". Trying to set a breakpoint results in a timeout:

```
Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:71:24)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
 1
Ln 11, Col 6Spaces: 2UTF-8 with BOMCRLFJavaScriptTeam 00
Attach (ymerclient)
Auto Attach: Off
```

When using this approach I get breakpoints in "react-scripts.js" file, however. So taht seems to be working. Not sure why I am not getting them in actual tests, however. For exhaustiveness, here is the code used in react-scripts.js that I can debug:
```

switch (script) {
  case 'build':
  case 'eject':
  case 'start':
  case 'test': {
    const result = spawn.sync(
      'node',
      nodeArgs
        .concat(require.resolve('../scripts/' + script))
        .concat(args.slice(scriptIndex + 1)),
      { stdio: 'inherit' }
    );

```

I reliable arrive at the "test" switch. Can the issue be due to the "spawn" statement?

**Comment by auchenberg** [comment]
What version of JEST are you using @MikaelUmaN ? I know @fallanic have been working on this in https://github.com/Microsoft/vscode-recipes/issues/107

**Comment by MikaelUmaN** [comment]
Jest version is 20.0.4 due to being a create-react-app scripts dependency. Hopefully they up it soon...

I was able to debug tests successfully using this approach:

From powershell, execute:
`node --inspect-brk .\node_modules\react-scripts\scripts\test.js --runInBand --no-cache --env=jsdom`

From vs code, launch using:

```
        {
            "type": "node",
            "request": "attach",
            "name": "Attach",
            "port": 9229
        },
```

So I'm relatively happy with that. The test.js script just does some minor stuff before calling jest.

Still I wanted to make it work directly from vscode, but so far no luck.

This config:
```
        {
            "name": "Debug CRA Tests",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "${workspaceRoot}/node_modules/react-scripts/scripts/test.js",
            "runtimeArgs": ["--runInBand", "--no-cache", "--env=jsdom"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector",
            "console": "internalConsole"
        },

```
ran into this in the terminal:

```
/node_modules/react-scripts/scripts/test.js --runInBand --no-cache --env=jsdom --inspect-brk=36455 
Error processing "launch": Error: spawn UNKNOWN
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:390:9)
    at NodeDebugAdapter.launchInInternalConsole (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:306:32)
    at NodeDebugAdapter.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:186:28)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Program Files\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\out\src\nodeDebugAdapter.js:7:58)
    at <anonymous>
 1
Ln 7, Col 1 (406 selected)Spaces: 4UTF-8LFJSON with CommentsTeam 00
Debug CRA Tests (ymerclient)
Auto Attach: Off
```

which I guess is a Windows problem... Suspecting it could be a nodejs version issue as well as it shows "7.9.0" when I check "About" in vscode, but my installed nodejs that I run from the terminal is 8.11.1. Best clue I can find is this: https://stackoverflow.com/questions/43419893/how-do-i-fix-error-spawn-unknown-with-node-js-v7-8-0-on-windows-10 .

So I might want to try installing nvs and setting runtimeVersion to 8+ rather than 7.9.0 which I suppose is begin run on now, though I don't know how to tell.

**Comment by fallanic** [comment]
@MikaelUmaN still having issues?

in your config you seem to be missing this `"program": "${workspaceFolder}/node_modules/.bin/jest",` which seems weird.

On my windows machine this configuration works with Jest 20.0.4 and the latest VS code

```
{
      "type": "node",
      "request": "launch",
      "name": "Jest All",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["--runInBand"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    },
```

**Comment by eddyekofo94** [comment]
Had this error for a very long time, after good long research here's my config which might help someone.

**package.json**
```
 "scripts": {
    "start": "node --inspect -r ts-node/register src/server.ts",
    "dev": "./node_modules/nodemon/bin/nodemon.js",
    "test": "jest",
    "test:watch": "jest --watch"
  }
```

**nodemon.json**

```
{
    "ignore": ["**/*.test.ts", "**/*.spec.ts", ".git", "node_modules"],
    "watch": ["src"],
    "exec": "npm start",
    "ext": "ts, gql",
    "inspect": true,
    "events": {
        "restart": "echo \"[Warning] Remember run npm run test b4 push to dev branch !\""
    }
}
```

**launch.json**
```
{
 "version": "0.2.0",
    "configurations": [{
        "type": "node",
        "request": "attach",
        "name": "Attach to Process",
        "port": 9229,
        "restart": true,
        "protocol": "inspector",
        // "processId": "${command:PickProcess}",
        "address": "localhost"
    }]
}
```

**Comment by MikaelUmaN** [comment]
Tried this again now on my local laptop. Latest node version 10.11.0 and VS code 1.28. This launch config:

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    },
    {
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
      "args": [
        "test",
        "--runInBand",
        "--no-cache"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}


And everything works perfectly.
