### ISSUE TITLE
Electron recipe: debug renderer without reloading page

### ISSUE THREAD

**Issue by alexk-z** [Microsoft/vscode-recipes#114]
Guys, first of all - thank you for your work! It helps a lot.

I would love to ask/brainstorm with you if debugging of renderer can be improved:
https://github.com/Microsoft/vscode-recipes/tree/master/Electron#debugging-of-the-renderer-process

> ...
> 4. Now go to your Electron app window and **reload the page** (View -> reload or CMD+R) to make sure the breakpoints are set.
> ...
> 

This reload breaks fast development cycles at the moment.

Can this reload be removed?

**Comment by auchenberg** [comment]
@alexk-z  This should have been resolved, as we have enabled break-on-load breakpoints by default. See  https://code.visualstudio.com/blogs/2017/12/20/chrome-debugging

**Comment by alexk-z** [comment]
In this case, Chrome is being launched by Electron. Does the recipe for Electron need to be updated? Or maybe `main.js` file?

I will try the simple Electron example referenced in the recipe to see if I can repro. In my project, I have to refresh Electron page to trigger breakpoints.

**Comment by DeekshithShetty** [comment]
@alexk-z Any updates on this? Even with the latest version of VS code I am not able to debug without reloading.
