### ISSUE TITLE
how to debug vue+typescript project create by vuecli3 ?

### ISSUE THREAD

**Issue by xxbld** [Microsoft/vscode-recipes#131]
i can breakpoint into *.ts file  ,but *.vue unsupport !

launch.json like this:
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
  ]
}

**Comment by Hammster** [comment]
I've stumbled on this while testing out vue-cli 3, the path for the sourcemap apperently changed a bit. I am not sure if this is a bug, but for now you can use my config from below to have breakpoints in node_modules and your own source.

![change](https://user-images.githubusercontent.com/1093709/47272926-beead980-d58c-11e8-9818-5a463ba0aee8.png)


```
{
            "type": "chrome",
            "request": "launch",
            "name": "vuejs: chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                // SourceMaps of own source
                "webpack:///./src/*": "${webRoot}/*",
                // SourceMaps of node_modules
                "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*"
            }
        }
```

**Comment by xxbld** [comment]
> I've stumbled on this while testing out vue-cli 3, the path for the sourcemap apperently changed a bit. I am not sure if this is a bug, but for now you can use my config from below to have breakpoints in node_modules and your own source.
> 
> ![change](https://user-images.githubusercontent.com/1093709/47272926-beead980-d58c-11e8-9818-5a463ba0aee8.png)
> 
> ```js
> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "chrome",
>             "request": "launch",
>             "name": "vuejs: chrome",
>             "url": "http://localhost:8080",
>             "webRoot": "${workspaceFolder}/src",
>             "breakOnLoad": true,
>             "sourceMaps": true,
>             "sourceMapPathOverrides": {
>                 // SourceMaps of own source
>                 "webpack:///./src/*": "${webRoot}/*",
>                 // SourceMaps of node_modules
>                 "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*"
>             }
>         }
>     ]
> }
> ```

thanks for your response !! and i did it.
BUT
*.vue file in  path < webpack:///./src/* >  is complied (one .vue complie to many *.vue?[hashcode] ) , debug will be mess.

**Comment by xxbld** [comment]
nice  !!!!!

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "vuejs: chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                // SourceMaps of own source
                "webpack:///./src/*": "${webRoot}/*",
                // SourceMaps of node_modules
                "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*"
            }
        }
    ]
}

AND

 vue.config.js

  configureWebpack: {
    devtool: 'source-map'
  },

**Comment by xxbld** [comment]
nice  !!!!!

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "vuejs: chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMaps": true,
            "sourceMapPathOverrides": {
                // SourceMaps of own source
                "webpack:///./src/*": "${webRoot}/*",
                // SourceMaps of node_modules
                "webpack:///./node_modules/*": "${workspaceFolder}/node_modules/*"
            }
        }
    ]
}

AND

 vue.config.js

  configureWebpack: {
    devtool: 'source-map'
  },
