### ISSUE TITLE
Angular with CLI attach instead of launch

### ISSUE THREAD

**Issue by chiangs** [Microsoft/vscode-recipes#132]
Is there a way to get the recipe to work via attach instead of launch?

**Comment by odahcam** [comment]
Yeah! I've done this before, but you still need to launch a new Chrome.

**Comment by chiangs** [comment]
well launching a new chrome instance with attach is sort of defeating the purpose right? i guess i'll just settle for launching or browser debugging until it's sorted out.

**Comment by auchenberg** [comment]
We can't put Chrome into debug mode when it's already running. This is a limitation of Chrome.

**Comment by odahcam** [comment]
> After 3 hours I wrote this comment, I'm finally sending it:

The reason for that is that Chrome starts without `--remote-debugging-port` enabled, so no one can listen to it. To just attach vscode's debugger to Chrome, it would have to be started everytime with `--remote-debugging-port` enabled, otherwise there's nothing for vscode's debugger to connect to.
