### ISSUE TITLE
Docker Typescript tutorial

### ISSUE THREAD

**Issue by oneturkmen** [Microsoft/vscode-recipes#140]
Hi there,

I have written yet another tutorial on debugging "dockerized" Node.js app with Typescript. Any option to add it along `Docker-Typescript` tutorial?

Here is the [link](https://github.com/oneturkmen/nodejs-debugging).

Thanks!

**Comment by GargantulaKon** [comment]
Thank you, since the one they have now seems old since they are using v0.1.0 of tasks in the example ReadMe.
