### ISSUE TITLE
Breakpoints move on after a restart server

### ISSUE THREAD

**Issue by Bubomir** [Microsoft/vscode-recipes#145]
Hi, I have a issue with breakpoints that jump on above lines after a server is restarting. For example I picked breakpoint on line 20, then everything working correct until server is not restarting then that breakpoint move on line above, for example line: 14. Does anyone idea why this is happening and how can i fix it ? Thank you for help

env:

    Win 10 Pro
    VS code: 1.28.0
    ts-node: 7.0.1
    nodemon: 1.18.4
    node: 8.12.0

Here is my config:
start script:

    "debug": "cross-env NODE_ENV=development nodemon -r --watch src dotenv/config --inspect -r ts-node/register src/index.js"

launch.json config:

    {
        "version": "0.2.0",
        "configurations": [{
	    	"type": "node",
		"request": "attach",
		"name": "Node: Nodemon",
		"processId": "${command:PickProcess}",
		"restart": true,
		"protocol": "inspector"
	    }]
    }

and ts config:

    {
	    "compilerOptions": {
		"module": "commonjs",
		"noImplicitAny": true,
		"allowJs": true,
		"target": "es2015",
		"noUnusedLocals": true,
    	"noUnusedParameters": true,
		"moduleResolution": "node",
		"inlineSourceMap": true,
		"typeRoots" : [
			"node_modules/@types",
			"./types"
		]
	},
	"include": [
		"./src/**/*"
	],
	"exclude": [
    	"node_modules"
	]
    }

**Comment by auchenberg** [comment]
Closing as the last comment has provided a solution.
