### ISSUE TITLE
Improving the `Chrome Debugging with Angular CLI`

### ISSUE THREAD

**Issue by VahidN** [Microsoft/vscode-recipes#16]
This is my config for debugging `Angular CLI` apps using ASP.NET Core 
```json
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome for dotnet build & ng build",
      "url": "http://localhost:5000",
      "runtimeArgs": [
        "--user-data-dir",
        "--remote-debugging-port=9222",
        "--disable-session-crashed-bubble"
      ],
      "sourceMaps": true,
      "trace": true,
      "webRoot": "${workspaceRoot}/wwwroot/",
      "userDataDir": "${workspaceRoot}/.vscode/chrome"
    }
```
Without specifying the `sourceMaps` and correct `webRoot` path to find them, the debugger is not able to show received items from the server.

**Comment by bjoernbusch** [comment]
Agreed, I also need the sourceMaps.

**Comment by auchenberg** [comment]
@VahidN The latest version of our Chrome debugger should be setting a `userDataDir` and enable `sourceMaps` for you by default. So unless you have very specific needs for your `userDataDir` you don't need those properties, 

@bjoernbusch What problems do you have with sourceMaps?

**Comment by bjoernbusch** [comment]
That source maps were not found until I added the sourceMaps attribute, now it's working fine.

**Comment by auchenberg** [comment]
@bjoernbusch What version of the Debugger for Chrome are you using? This shouldn't be the case.

**Comment by auchenberg** [comment]
@bjoernbusch Alright, if you have any issues please open issues on https://github.com/Microsoft/vscode-chrome-debug, as this is strictly about documentation for `angular-cli`

**Comment by ianqueue** [comment]
so i like this, but running into an issue where the debugger is hitting generated html files etc. `FlowsModule/ng:FlowsModule/FlowsComponent_Host.html` I also have to ignore directories like certain node_modules etc.

Am I doing something wrong here?  this is supposed to be out of the box config for angular cli development so I am curious if anyone has run into this as I want to just see references to my code execution. thanks.

**Comment by auchenberg** [comment]
@ianqueue Can you open an issue on https://github.com/Microsoft/vscode-chrome-debug, with the details on your setup and then we can take it from there? I'd like to avoid "polluting" exising issues.
