### ISSUE TITLE
Debugging npm run test doesnt work - Unverified breakpoint

### ISSUE THREAD

**Issue by WtfJoke** [microsoft/vscode-recipes#175]
I followed the receipe/tutorial of https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI. 

I can debug the normal code using npm start and breakpoints get hit.

However debugging tests like described [here](https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI#debug-unit-tests) doesnt work.

As soon I launch ng test from debugging view , the breakpoint in the test is suddenly unverified.
Whats also strange is that in the chrome which opens the debug site, I need to manually hit refresh to display something. 

Do you have any idea?

OS: Windows 10
Angular-CLI: 7.0.2
VS-Code: 1.29.1 (system setup)
Debugger for chrome: 4.11.1

**Comment by kuzditomi** [comment]
+1

**Comment by WtfJoke** [comment]
This might get closed/fixed by #179.

**Comment by WtfJoke** [comment]
This config works for me 😄 
```
     {
        "name": "ng test",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:9876/debug.html",
        "webRoot": "${workspaceFolder}",
        "sourceMaps": true,
        "sourceMapPathOverrides": {
          "/./*": "${webRoot}/*",
          "/src/*": "${webRoot}/*",
          "/*": "*",
          "/./~/*": "${webRoot}/node_modules/*"
        }
      }
```

**Comment by joshvito** [comment]
I run in a console `node ./node_modules/@angular/cli/bin/ng run APPNAME:test --watch=true --source-map`
Then, when I run the config that @WtfJoke supplied above, I get the following error from VS Code
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a valid target that matches: about:blank. Available pages:  ...`

If I manually open `http://localhost:9876/debug.html` after running the above mentioned `ng run ...test` command, then launch the above config via vs code, I get the same error.

If I attempt to attach to an existing process via VS Codes attach config , e.g.
```
{
      "type": "chrome",
      "request": "attach",
      "name": "Attach to Chrome",
      "port": 9222,
      "webRoot": "${workspaceFolder}"
    },
```
I can pick the opened browser tab of `http://localhost:9876/debug.html`, but the breakpoints I have added in my unit test code are now grayed out and not verified.

Trying the below config, results in the same unverified breakpoint problem too.
```
{
        "name": "ng test",
        "type": "chrome",
        "request": "attach",
        "url": "http://localhost:9876/debug.html",
        "webRoot": "${workspaceFolder}",
        "sourceMaps": true,
        "sourceMapPathOverrides": {
          "/./*": "${webRoot}/*",
          "/src/*": "${webRoot}/*",
          "/*": "*",
          "/./~/*": "${webRoot}/node_modules/*"
        }
      }
```

![image](https://user-images.githubusercontent.com/1249866/50524902-5f3a0e80-0aa6-11e9-80df-37d5b6e2bbe9.png)

**Comment by WtfJoke** [comment]
I think you have another issue on your end @joshvito 

Neverthless try following:
With my provided config you simply start tests by running just `ng test` in your console (if you havent installed angular probably `./node_modules/@angular/cli/bin/ng test` does the trick as well). Then a chrome browser should pop up running all your tests. 

After that, set your breakpoints in tests and start  the "ng test" launch config in vs code. Then an additional chrome pops up and your breakpoints should get hit and there shouldnt be unverified breakpoints anymore.

**Comment by joshvito** [comment]
When the second browser opens, it doesn't navigate anywhere. Empty address bar, then I get the timeout error message. Shouldn't the second browser be navigating to the url defined in the debug profile?

**Comment by krbaio3** [comment]
me too, I followed the tutorial of [Microsof](thttps://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI), I modify the config like @WtfJoke suggest: 
```
{
      "name": "ng test",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "/./*": "${webRoot}/*",
        "/src/*": "${webRoot}/*",
        "/*": "*",
        "/./~/*": "${webRoot}/node_modules/*"
      }
    },
```
, but, when run the debug config, the break points are unverified, and in loader Scripts section of VS code, I can see this foldels:
![captura de pantalla de 2019-01-14 21-38-16](https://user-images.githubusercontent.com/22777201/51139653-c4cb2080-1844-11e9-91c0-0af2d02ef9be.png)


My ng config is:

```
Angular CLI: 7.2.1
Node: 10.15.0
OS: linux x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.1
@angular-devkit/build-angular      0.12.1
@angular-devkit/build-ng-packagr   0.12.1
@angular-devkit/build-optimizer    0.12.1
@angular-devkit/build-webpack      0.12.1
@angular-devkit/core               7.2.1
@angular-devkit/schematics         7.2.1
@angular/cdk                       7.2.1
@angular/cli                       7.2.1
@angular/material                  7.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.1
@schematics/angular                7.2.1
@schematics/update                 0.12.1
ng-packagr                         4.5.0
rxjs                               6.3.3
typescript                         3.2.2
webpack                            4.23.1
    
```

**Comment by MikeJerred** [comment]
I also have the same issue, the browser opens and does not navigate anywhere, and then I get the error popup "Cannot connect to runtime process, timeout after 10000ms - (reason: Can't find a valid target that matches: about:blank. Available pages: ["http://localhost:9876/?id=77064511"])."

**Comment by prabh-62** [comment]
This is how I got unit test debugging working within VS Code

```bash
> npx @angular/cli@next new dream-app
 # this command should install version 8.0.0-beta.7 of @angular/cli as of March 21, 2019
```

After creating the project, look in `package.json`, jasmine-core version should be >= 3.3.0
```json
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
```
> If you already have an angular project, just update these test dependencies.


Your VSCode Debug config(`.vscode/launch.json`) should look like this:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "ng test",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

```bash
> npm test
```
Now, start debugging through VS Code. Set breakpoints in any *.spec.ts file
<img width="1118" alt="breakpoint" src="https://user-images.githubusercontent.com/13006107/54795206-98a39580-4c21-11e9-8b4f-488b4ab88a00.png">



<hr/>

**Note:** :gun:

Make sure you don't have `code coverage` enabled in tests during development. Even though breakpoints would be correctly set for `*.spec.ts` files, breakpoints would be incorrectly mapped for `*.component.ts` file. Explanation: [Disable Code Coverage in dev mode](https://glebbahmutov.com/blog/debugging-karma-unit-tests/)

> In CI, you could do something like for enabling code coverage (Angular CLI 8)
```json
  "scripts": {
    "test:ci": "ng test --no-watch --no-progress --code-coverage"
	}
```

**Comment by briancodes** [comment]
I have a clean project setup using `Angular CLI 7.3.8`, and followed the debugging setup [instructions](https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI)  (at the time last updated Feb 27, 2019) - the `ng serve` debugging worked, but when debugging with `ng test` the breakpoints were not being hit

I added `"webpack:/*": "${webRoot}/*"` to the `launch.json` `sourceMapPathOverrides` for `ng test` and the breakpoints were then hit. This was a known fix for a pervious version of the CLI too

```
"sourceMapPathOverrides": {
	"webpack:/*": "${webRoot}/*",
	"/./*": "${webRoot}/*",
	"/src/*": "${webRoot}/*",
	"/*": "*",
	"/./~/*": "${webRoot}/node_modules/*"
},
```

**Comment by kvbutler** [comment]
@prabh-62 is right codeCoverage: true in angular.json breaks debugging. Thanks!

**Comment by auchenberg** [comment]
Recipe updated in https://github.com/microsoft/vscode-recipes/pull/212
