### ISSUE TITLE
Recipe request: Angular-CLI & Docker-Typescript combined

### ISSUE THREAD

**Issue by cilerler** [microsoft/vscode-recipes#18]
Would you please create a combined recipe of [Angular-CLI](https://github.com/weinand/vscode-recipes/tree/master/Angular-CLI) and [Docker-Typescript](https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript)

Thanks in advance 🤗

**Comment by connor4312** [comment]
docker-typescript has been supplanted by VS Code's remote development workflows.
