### ISSUE TITLE
vue-cli recipe - shouldn`t there be a prelaunchTask for npm run serve ?

### ISSUE THREAD

**Issue by tuath** [Microsoft/vscode-recipes#184]
I am looking at this and although starting Chrome is nice, but it "assumes" that i`ve done a npm run serve.

Shouldn`t this be managed by a task which runs in the background as a prelaunchTask ?

I am trying to figure this one out, but am having problems defining the task:
{
            "label": "npmServe",
            "type": "npm",
            "script": "serve",
            "path": "VUE.Web/",
            "problemMatcher": {
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "",
                    "endsPattern": ""
                }
            },
            "isBackground": true
            //"runOptions": { "runOn": "folderOpen"},
        }

I think it should be a part of the recipe...

**Comment by auchenberg** [comment]
Step two in the guide explicitly says run `npm start`, but feel free to contribute an alternative version so people have the choice.
