### ISSUE TITLE
Not working: Electron debugging (main and renderer process)

### ISSUE THREAD

**Issue by lgLindstrom** [Microsoft/vscode-recipes#186]
I've followed the steps,, but break point on line 6 is not active so execution never stops.
If I start with configuration Electron:All, both breakpoints are active, but execution only stops in Main process.

So, any good ideas ... ??

Versions
Electron v4.01
Node v10.15.0
Vs code 1.30.2
Debugger for chrome 4.11.1

**Comment by auchenberg** [comment]
What if you refresh the renderer process after the breakpoint as been set? Or if you set a breakpoint in later executed code such as a click event handler? @lgLindstrom

**Comment by lgLindstrom** [comment]
The example is quite small,, so I can't set any later breakpoint (Hope I did understand you?)
I have refreshed the renderer process by using CTRL-R. Also I restarted the Restarted debugger after setting breakpoints,,,  
Breakpoints are still disabled in the renderer process.....

**Comment by lgLindstrom** [comment]
Hi.
It have been a while but I am sitting with the same problem but at a much higher level :)
I clone this as a start template  https://github.com/maximegris/angular-electron.git

Main process is easy to debug,,, works well.
Renderer process is a mess..   all breakpoints in the renderer process is disabled and the debugger fails with message ".... cant connect ........".

**Comment by xmedeko** [comment]
It works, but I have to:
# Call `test()` inside `DOMContentLoaded` event.
# Go to Electron and do reload the view Ctrl+R.

And that's a bit inconvenient. Is it possible to debug the renderer process just from the start?

**Comment by connor4312** [comment]
Please open an issue here if you are still having trouble: https://github.com/microsoft/vscode-js-debug/issues/new/choose
