### ISSUE TITLE
Debugging test "Jest current file" doesn't work

### ISSUE THREAD

**Issue by daton89** [microsoft/vscode-recipes#189]
Using your suggested launch script for current file is not working: 

``` json
 {
      "type": "node",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["${relativeFile}"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    }
```
I get this error: 
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).`

This is because jest needs to have the option --ìnspect-brk` before the jest bin.

So refactoring the launch.json like this make it works.

``` json
        {
            "type": "node",
            "request": "launch",
            "name": "Jest Current File",
            "args": [
                "--inspect-brk",
                "${workspaceFolder}/node_modules/.bin/jest",
                "${relativeFile}",
                "--runInBand"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest"
            },
            "port": 9229
        },
```

**Comment by auchenberg** [comment]
@daton89 See the updated steps, and let me know how that works, https://github.com/Microsoft/vscode-recipes/blob/master/debugging-jest-tests/README.md

**Comment by tbn-mm** [comment]
It works, at least for current file.

**Comment by connor4312** [comment]
Please open an issue here if you are still having trouble: https://github.com/microsoft/vscode-js-debug/issues/new/choose
