### ISSUE TITLE
Debugging a ruby application with child processes

### ISSUE THREAD

**Issue by senhalil** [Microsoft/vscode-recipes#199]
Hello  I am trying to debug an application which uses `rake resque:workers`. I can follow the code untill the fork (shown in the image)  and cannot enter the child processes. I can see the call stack of the main thread (2); however, cannot interact with the remaining threads (83-87). 

Unfortunately the code I need to debug runs in the child processes and triggered when a task is submitted. 

![vscode](https://user-images.githubusercontent.com/20163961/53794955-3b28fc80-3f31-11e9-8058-22d6e000efa2.jpg)

Here is how my `launch.json` config looks like
```
        {
            "name": "Workers",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "/home/halil/.rbenv/versions/2.1.8/bin/rake",
            "useBundler": true,
            "env": {
                "COUNT": "5",
                "QUEUE": "*"
            },
            "args": ["resque:workers"]
        },
```
The moment I let the code continue (i.e., let it call the `thread.join()` on all threads) either with F5 or F11 (in fact F11 does nothing different) one of the threads picks up the submitted task, runs the code (which I want to debug) and prints out the result without giving me any chance to debug.

I also tried starting the worker process outside of the vscode with `COUNT=5 QUEUE=* rdebug-ide --port 1234 --host 0.0.0.0 -- /home/halil/.rbenv/versions/2.1.8/bin/bundle exec rake resque:workers` and attached the debugger with the following launch config:
```
        {
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "showDebuggerOutput": true,
            "remoteHost": "0.0.0.0",
            "remotePort": "1234",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }
```
This again lets me to follow the code till the fork and I cannot see the workers.

I would really appreciate if you have an idea about how to debug such an application.

**Comment by auchenberg** [comment]
Hi @senhalil 

This is really a question for https://github.com/rubyide/vscode-ruby/issues, as we don't maintain the Ruby extension and debugger.

**Comment by auchenberg** [comment]
This issue was moved to rubyide/vscode-ruby#448
