### ISSUE TITLE
No tests found - testMatch: 0 matches

### ISSUE THREAD

**Issue by lackovic** [Microsoft/vscode-recipes#200]
### Environment

1. node: `10.15.0`
2. npm: `6.4.1`
3. react-scripts: `2.1.3`
4. Operating system: `Windows 10 1809 17763.316`
5. Visual Studio Code: `1.31.1`

### launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Jest Current File",
      "program": "${workspaceFolder}/node_modules/.bin/jest",
      "args": ["${relativeFile}"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "disableOptimisticBPs": true,
      "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
      }
    }
  ]
}
```
### jest.config.js
```
module.exports = {
  testMatch: [
    '**\\*test.tsx',
    '**/*test.tsx',
    'src\\**\\*.test.tsx',
    'src/**/*.test.tsx',
    '<rootDir>\\src\\**\\*.test.tsx',
    '<rootDir>/src/**/*.test.tsx',
    'src/.*|(.|/)(.test).tsx?$'
  ],
};
```

Running _Jest Current File_ in Visual Studio Code on an opened test file (`List.test.tsx`) produces the following output:
```
cd 'c:\src\path'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=24849' 'node_modules\jest\bin\jest.js' 'src/path/List.test.tsx'
Debugger listening on ws://127.0.0.1:24849/8b545492-34e9-4a3d-b6f1-e8e7dcc71421
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
No tests found
In C:\src\path
  34 files checked.
  testMatch: **\*test.tsx,**/*test.tsx,src\**\*.test.tsx,src/**/*.test.tsx,C:\src\path\src\**\*.test.tsx,C:\src\path\src\**\*.test.tsx - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 34 matches
Pattern: src\\path\\List.test.tsx - 0 matches
Waiting for the debugger to disconnect...
```

**Comment by lackovic** [comment]
I don't think the problem is with the launch configuration itself, as when trying to run the test from command line with `npx jest src/path/List.test.tsx` I get the same result:
```
No tests found
In C:\src\path
  34 files checked.
  testMatch: **\*test.tsx - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 34 matches
Pattern: src\\path\\List.test.tsx - 0 matches
```

**Comment by blamay** [comment]
I just started getting this same problem after updating VSCode to 1.32.1. I'm not 100% sure what I was on before then. It still works on Mac with the latest version, so if you can, I recommend testing your launch configuration on Mac VSCode to confirm that it's not a problem with your configuration.

**Comment by lackovic** [comment]
@blamay might be that I was actually on `1.32.1`, I am not sure about that.

Your problem might have been fixed with https://github.com/firsttris/vscode-jest-runner/pull/19

Looks like my problem is related with [create-react-app](https://github.com/facebook/create-react-app) which was used to build the project. See [this stackoverflow question](https://stackoverflow.com/questions/54052509/jest-from-create-react-app-not-running-on-windows).
