### ISSUE TITLE
Mocha: `opts` and node options such as `require`

### ISSUE THREAD

**Issue by mhofman** [microsoft/vscode-recipes#206]
Since the `launch.json` uses the `_mocha` launcher, the node options present in any `opts` file will not be passed to the node process which is invoked directly by VSCode.

At the very least this should be documented. But I'd love to find a solution to avoid replicating my `opts` content in `launch.json`

support/mocha.opts:
```
-- require esm
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Test All with Options",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "--opts", 
                "${workspaceFolder}/support/mocha.opts",
                "${workspaceFolder}/test"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
    ]
}
```

**Comment by connor4312** [comment]
mocha.opts has been replaced with .mocharc, which seems to be loaded by _mocha without issues.
