### ISSUE TITLE
Debugging jest in Windows, breakpoint does not hit .ts source file

### ISSUE THREAD

**Issue by indcoder** [microsoft/vscode-recipes#220]
While using the Jest script for debugging a Typescript npm module, the debugger successfully hits the breakpoint in the test file but does not not hit the breakpoint in the source .ts file under test.

**Comment by FishOrBear** [comment]
I encountered the same problem, it was originally a break point.

**Comment by chrisdias** [comment]
Do you have a sample that demonstrates this?

**Comment by FishOrBear** [comment]
[JestDebugTest.zip](https://github.com/microsoft/vscode-recipes/files/3350418/JestDebugTest.zip)
@chrisdias

**Comment by indcoder** [comment]
> Do you have a sample that demonstrates this?

Even better, a whole repo :-) . Please check -< https://github.com/indcoder/eventbrite-checkins.
As mentioned I can step into the breakpoint in the test.spec file but not into the source .ts file.

**Comment by FishOrBear** [comment]
https://github.com/facebook/jest/issues/7842

solve this problem

```
   {
            "type": "node",
            "request": "launch",
            "name": "Jest Current File",
            "program": "${workspaceFolder}/node_modules/.bin/jest",
            "args": [
                "${relativeFile}",
                "--config",
                "jest.config.js",
                "--testMatch",
                "**/?(*.)+(spec|test).[jt]s?(x)"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "disableOptimisticBPs": true,
            "windows": {
                "program": "${workspaceFolder}/node_modules/jest/bin/jest",
            }
        }
```

**Comment by roblourens** [comment]
@indcoder if you try it in chrome devtools you will see that it doesn't work there either. You have code coverage enabled which seems to be disabling sourcemap generation.

If I disable that in jest.config.js with `collectCoverage: false` then it works fine in VS Code for me
