### ISSUE TITLE
Unit test launch configuration is missing path mapping 

### ISSUE THREAD

**Issue by tasdevani21** [microsoft/vscode-recipes#253]
Using the instructions found in the Angular CLI for debugging, I am able to run ng serve and ng e2e with breakpoints however I am not able to run ng test with the breakpoints with the instructions provided. 

Upon further investigation, I found that it is missing `pathMapping` for `karma_webpack` which caused it to not resolve the files that it needed.       

```
    "pathMapping": {
        "/_karma_webpack_": "${workspaceFolder}"
    }

```

The updated ng test configuration looks like the following and works for me:

```
    {
      "name": "ng test",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
      "pathMapping": {
        "/_karma_webpack_": "${workspaceFolder}"
      },
      "sourceMapPathOverrides": {
        "webpack:/*": "${webRoot}/*",
        "/./*": "${webRoot}/*",
        "/src/*": "${webRoot}/*",
        "/*": "*",
        "/./~/*": "${webRoot}/node_modules/*"
      }
    }

```

Angular Version: 9.0.3

**Comment by reyou** [comment]
This must go in PR. This fixed my issue as well, thanks!

**Comment by s4m0r4m4** [comment]
Yes this helped me too! I tried to put it in a PR but looks like I don't have permission...

Also - the current instructions result in opening a window twice (once when you do `npm run test`, and again when you run the debug configuration `ng test`). I think the recipe should attach to the existing chrome instance, as described here: http://blog.mlewandowski.com/Debugging-Karma-tests-with-VSCode.html (though I couldn't quite get that to work...).

Also, the following line in the instructions is not clear:
_"After the test run, go to the Debug view, select the 'ng test' configuration, then press F5 or click the green button."_ --> is this talking about the green debug button in VS code or the green debug button in the chrome browser opened by Karma?

**Comment by VitaliyDushko** [comment]
You literally saved my day. You are the best!

**Comment by libinvarghese** [comment]
Also solves #240

**Comment by libinvarghese** [comment]
Related to #225

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-recipes/issues/225
