### ISSUE TITLE
Do two simultaneous breakpoints in two different debug processes work?

### ISSUE THREAD

**Issue by leontepe** [microsoft/vscode-recipes#258]
I am using the VS Code recipe for Electron and I finished the guide. But at the end, if I just launch the `Electron: All` debug configuration and leave both the breakpoint in `main.js` and in `renderer.js`, VS Code only breaks at the one in `main.js` (main process).

Is there a reason for this? Is this the intended result or am I doing something wrong? Also, is there another way to "combine" the breakpoints without having to reload the page first?

**Comment by connor4312** [comment]
Please open an issue here if you are still having trouble: https://github.com/microsoft/vscode-js-debug/issues/new/choose
