### ISSUE TITLE
TypeScript Docker debugging broken after latest update

### ISSUE THREAD

**Issue by aecorredor** [microsoft/vscode-recipes#265]
After updating to the latest VSCode version which introduced the new JS debugger, our current setup broke. The setup followed this recipe: https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript.

Any clues on what changed and what can be done to update the config for this setup to work again?

Downgrading VSCode versions was our solution for now.

**Comment by aecorredor** [comment]
@chrisdias any news on this?

**Comment by chrisdias** [comment]
hey @connor4312 any ideas?

**Comment by aecorredor** [comment]
@chrisdias @connor4312 sorry guys, I just saw that this commit was added 15 days ago marking the recipe as obsolete: https://github.com/microsoft/vscode-recipes/commit/c31ba7a0f66316ee98804b76accd692036c13ff4#diff-06b517966e09542fbde5ca978b61dc0b
