### ISSUE TITLE
Docker-TypeScript unbound breakpoint

### ISSUE THREAD

**Issue by rotemironsrc** [microsoft/vscode-recipes#266]
took your project as is, and breakpoint never get hit while debugging.

vscode June 2020 (version 1.47)

**Comment by hurulis** [comment]
+1 , same here

**Comment by alanbo** [comment]
+1, same here

**Comment by weinand** [comment]
Does it make a difference if you disable our new js-debugger by adding a `"debug.javascript.usePreview": false` to your settings?

**Comment by rotemironsrc** [comment]
Nope,  but i now know that the problem is, when you open the window to show
all the folders, and then try to debug.

**Comment by rotemironsrc** [comment]
also it doesn't work with workspace.

**Comment by weinand** [comment]
Yes, make sure to only open the `Docker-TypeScript` folder in VS Code and not the enclosing recipes folder.

BTW, the `Docker-TypeScript` is outdated (and obsolete).  It was created in a time when VS Code did not have universal [remote development capabilities](https://code.visualstudio.com/docs/remote/remote-overview) and only its Node.js debugger was able to debug remotely.
Today we recommend to use VS Code's excellent [container development support](https://code.visualstudio.com/docs/remote/containers).
With this, TypeScript development in a Docker container is not different than TypeScript development in a local setup.

**Comment by rotemironsrc** [comment]
i need a way to debug in workspace, i want to able to debug multiple
services inside the docker from one window.
is it possible?

**Comment by weinand** [comment]
If you use a multi-folder workspace setup for the different services, you can debug them in different debug sessions within one window.

**Comment by rotemironsrc** [comment]
how ? can you send me a reference ?
i have a docker-compose file for all of my services
i have a workspace containing separate folders for each service i have. 
in each folder i have .devcontainer folder with devcontainer.json and docker-compose and a dockerfile
but i see the only way to debug each service i need to open each one in a new window.

**Comment by rotemironsrc** [comment]
Currently you can only connect to one container per VS Code window
according to your documentation it is not possible yet.

**Comment by suhaasprasad** [comment]
Have you found any workarounds?

**Comment by suhaasprasad** [comment]
Have you found any workarounds?

**Comment by suhaasprasad** [comment]
Any update here?

**Comment by weinand** [comment]
As said already above:

The `Docker-TypeScript` recipe is outdated (and obsolete).  It was created in a time when VS Code did not have universal [remote development capabilities](https://code.visualstudio.com/docs/remote/remote-overview) and only its Node.js debugger was able to debug remotely.
Today we recommend to use VS Code's excellent [container development support](https://code.visualstudio.com/docs/remote/containers).
With this, TypeScript development in a Docker container is not different than TypeScript development in a local setup.
