### ISSUE TITLE
mern starter recipe not working

### ISSUE THREAD

**Issue by FrancisVila** [microsoft/vscode-recipes#269]
1. I tried the simple instructions in the [mern starter ](https://github.com/microsoft/vscode-recipes/tree/master/MERN-Starter)recipe.
2. got to npm install. First I got an error message. Searching for the solution, I fell on this article:
    https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c
    it says: _Use the Visual Studio Installer to get the Desktop development with C++ workload in one of the Visual Studio versions you have installed in your machine_
3.  launched the installer, but did not see the C++ module
4. updated  the VS Studio Installer, the C++ module appeared, I added it in and rebooted (this takes a long time)
5. ran npm install again. Different error this time. This is the start, after that it goes on and on:
`
c:\projects\mern-starter\node_modules\nan\nan_implementation_12_inl.h(103,37): error C2664: 'v8::MaybeLocal<v8::Functio
n> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::S
ideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\l
ib\index.cpp) [c:\projects\mern-starter\node_modules\nodejieba\build\nodejieba.vcxproj]
c:\projects\mern-starter\node_modules\nan\nan_implementation_12_inl.h(105,32): message : No constructor could take the
source type, or constructor overload resolution was ambiguous (compiling source file ..\lib\index.cpp) [c:\projects\mer
n-starter\node_modules\nodejieba\build\nodejieba.vcxproj]
C:\Users\fvila\AppData\Local\node-gyp\Cache\12.17.0\include\node\v8.h(4275,31): message : see declaration of 'v8::Funct
ion::New' (compiling source file ..\lib\index.cpp) [c:\projects\mern-starter\node_modules\nodejieba\build\nodejieba.vcx
proj]
c:\projects\mern-starter\node_modules\nan\nan_implementation_12_inl.h(103,37): error C2664: 'v8::MaybeLocal<v8::Functio
n> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::S
ideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\l
ib\nodejieba.cpp) [c:\projects\mern-starter\node_modules\nodejieba\build\nodejieba.vcxproj]
`

**Comment by connor4312** [comment]
This doesn't appear to be an issue with vscode.
