### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by oneolddev** [Microsoft/vscode-recipes#315]
The link to _Debugging Typescript in Docker Container_ in the README.md at the root of the repository is broken.

![image](https://user-images.githubusercontent.com/23250332/137595930-82c0dba6-3e9c-4851-8495-5b530f5085e4.png)

**Comment by gregvanl** [comment]
Fixed with https://github.com/microsoft/vscode-recipes/commit/d9cc70819e845ac684793e7da071cde56e2f87f6
Thanks for pointing this out.
