### ISSUE TITLE
`attach` configuration for Nodemon

### ISSUE THREAD

**Issue by iocalebs** [Microsoft/vscode-recipes#332]
Is there a way to attach a debugger to a running Node process, such that the debugger re-attaches itself when Nodemon restarts the process on save?

The current recipe [recommends an `attach` configuration](https://github.com/microsoft/vscode-recipes/blob/f6a2e597e079ae9f7d55cc5ed7975e21a86fcf68/nodemon/README.md?plain=1#L9) but provides only a `launch` configuration. It seems the `attach` configuration was removed in order to fix #273. 

It would be nice to have an `attach` configuration for those who wish to start the app in a terminal and run/attach the VS Code debugger only when needed.

**Comment by iocalebs** [comment]
This configuration works for attaching to the Node process but the debugger dies on save, presumably due to Nodemon killing the process and starting a new one. Setting `restart: true` doesn't work, again presumably because it tries to attach to the old process instead of the new one.
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Node: Nodemon",
      "processId": "${command:PickProcess}"
    }
  ]
}
```

**Comment by devopsinvictus** [comment]
`npm run debug`

**Comment by iocalebs** [comment]
omg I can't believe it's that simple...

Is this behaviour documented somewhere in VS Code docs?
