### ISSUE TITLE
Add recipe for Jest

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-recipes#37]
Per https://github.com/Microsoft/vscode/issues/19566

**Comment by auchenberg** [comment]
Jest docs: https://facebook.github.io/jest/docs/en/troubleshooting.html#debugging-in-vs-code

**Comment by jagreehal** [comment]
Hey @auchenberg I've created a PR for how to debug tests using VS Code https://github.com/Microsoft/vscode-recipes/pull/53

**Comment by auchenberg** [comment]
Landed in https://github.com/Microsoft/vscode-recipes/pull/53
