### ISSUE TITLE
Debugger is not working in VS code

### ISSUE THREAD

**Issue by vishalpwankhede** [Microsoft/vscode-recipes#54]
Hi,
I am not able to debug in VS code for my project(was working before).

Throwing error: (node:24328) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead

VS Code details:
Version 1.19.1
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Node version: v9.2.1

Thanks

**Comment by auchenberg** [comment]
This issue was moved to Microsoft/vscode-node-debug2#161
