### ISSUE TITLE
Meteor recipe / git clone errors out

### ISSUE THREAD

**Issue by ChuckIrvine** [Microsoft/vscode-recipes#57]
The recipe says to execute:

`git clone git@github.com:meteor/simple-todos-react.git`

This gives me:

```
Cloning into 'simple-todos-react'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I'm not a git or github expert. Might be my problem.

**Comment by auchenberg** [comment]
Please follow the instructions on https://github.com/meteor/simple-todos-react by clicking the "download/clone" button. 

GitHub has great docs on how git clone works https://help.github.com/articles/cloning-a-repository/

**Comment by ChuckIrvine** [comment]
Well, I’m not that much of a git newbie. :-) 

It might be advisable to modify the recipe to use:

git clone https://github.com/meteor/simple-todos-react.git <https://github.com/meteor/simple-todos-react.git>

Another small gotcha. The timeout setting of 30000 was too short for me. I changed it to 60000 and it worked. 

Thanks
