### ISSUE TITLE
Next-js recipes not working

### ISSUE THREAD

**Issue by mellet** [Microsoft/vscode-recipes#63]
I'm trying to set up debugging for Next.js.

Using the following package.js:
```
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "debug": "next --inspect"
  },
  "dependencies": {
    "next": "^4.2.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

The first time I tried to start debugging in VSCode it could not find next, so I tried installing it globally.
This just resulted in:
```
user$ cd /nextdebugtest ; /usr/local/bin/next --inspect
The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install --save react-dom'
Error: Cannot find module 'react'
```

So I tried modifying the debug config to this:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Next: Node",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run-script", "debug"],
      "port": 9229,
      "console": "integratedTerminal"
    },
    {
      "type": "chrome",
      "request": "launch",
      "name": "Next: Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}"
    }
  ],
  "compounds": [
    {
      "name": "Next: Full",
      "configurations": ["Next: Node", "Next: Chrome"]
    }
  ]
}

```
It starts next fine, but gets a timeout that it can't connect to port 9229.
`Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).`

When trying to run just next with `next --inspect` and browsing to `http://localhost:9229/json/version` I'm just getting `This site can’t be reached`.

Might be that Next.js has done some changes since this config was created.

**Comment by mellet** [comment]
Figured out that I have to run on the canary build of next.
From the docs I just assumed that version **4.2.3** would be newer than **Next.js 4.2.0-canary.1** from the docs. But that is not the case.

**Comment by auchenberg** [comment]
Yes it's dependent on this PR I opened for next, https://github.com/zeit/next.js/pull/3294, hence the reason for why we explicitly call out the canary version in next.

Hopefully this lands in next stable.
