### ISSUE TITLE
Can't debug meteor with a custom setttings file

### ISSUE THREAD

**Issue by arlohosk** [Microsoft/vscode-recipes#66]
I'm having an issue with hitting breakpoints (i.e. able to do `meteor run --inspect` and the node inspector process runs, but it is not linking to my source code break points).

Meteor version: 1.6.0.1
Node version: v8.9.3
NPM version: 5.5.1

File Structure: standard suggested meteor project with /imports as the main folder; Package.json file is at the root of the project. Settings file is outside in a separate folder (I run it with `--settings ../pathToSettings/settingsFile.json`)

My full launch.json looks like this:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Meteor: Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Meteor: Node",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run", "debug"],
            "port": 9229,
            "timeout": 30000
        }
    ],
    "compounds": [
        {
            "name": "Meteor: All",
            "configurations": ["Meteor: Node", "Meteor: Chrome"]
        }
    ]
}
```
-----
Aside from the dependencies block w/ meteor packages, below is all i have in my package.json (names edited for simplicity - the settings file is definitely being read as I use it from the terminal. It is required to start the app properly.)

**NOTE:** I think the package.json file in Meteor is also used for Prod deployment. How would I specify the settings file path in the launch.json rather than here, so that it doesn't interfere with my Prod deployment?

```

  "name": "appName",
  "private": true,
  "scripts": {
    "start": "meteor run --settings ../pathtosettings/settingsfile.json",
    "debug": "meteor run --inspect --settings ../pathtosettings/settingsfile.json"
  },

```

Any ideas how to start debugging?

**Comment by auchenberg** [comment]
@arlohosk Can you provide a gist of your folder structure of your project? I'm not sure whether your app is under `/imports` or how it's structured.

Also can you try to run the `.scripts` command as outlined here https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command, and provide the output here? This will give us an idea of the paths used in the generated sourcemap.

**Comment by arlohosk** [comment]
sorry, yes for more clarity, the root folder of my project looks like this:

```
client
server
imports (this contains the meat of the app)
private
public
packages
package.json
.meteor
.vscode
```

It is roughly what is suggested under **Example directory layout** here: https://guide.meteor.com/structure.html

I will run the .scripts command later tonight or tomorrow morning and let you know. Thanks for your continued help!

**Comment by arlohosk** [comment]
Hi, sorry for the delay.

1) I cant figure out how to run run meteor with my settings file. 
When I try to put the path in settings.json, it just gives me the standard ERROR Cannot Connect`.

2) When I run it with `meteor run --inspect --settings ../path/settings.json`  via a terminal inside VSCode,  then go to the Debug Console, it just says "please start a debug session"

**Comment by arlohosk** [comment]
@auchenberg 
Is this a separate issue from sourcemapping now - is there no actual way to run it with the --settings flag?

**Comment by auchenberg** [comment]
I just pulled the standard meteor react example project, added the usage of custom settings and can validate that breakpoints in both the server and client-side code can be hit, as expected.

Please https://github.com/auchenberg/meteor-simple-todos-react-custom-settings, and feel free to re-open this issue if you can't get it working on your machine. If you can, I suspect you have a problem in your specific project.

**Comment by arlohosk** [comment]
I noticed in that project, you had the following, without a folder path
```
  "scripts": {
    "start": "meteor run --settings settings.json",
    "debug": "meteor run --inspect --settings  settings.json"
  }
```
Do you know how to specify the folder path properly, so that it runs from within VSCode? That was the issue I was having - it wouldn't find the settings file. Both relative paths like `../` with commandline syntax and absolute paths starting with `D:/` failed for me.

I need to keep  my settings files in a separate repo, to track changes to them (many versions, lots of settings)

Thanks for any insight you can offer

**Comment by auchenberg** [comment]
I don't, and this isn't a VS Code problem but related to NPM and how you run NPM scripts with relative paths. See https://github.com/npm/npm/issues/13789

Alternative you can launch meteor from your terminal and attach the Node debugger from VS Code.

**Comment by arlohosk** [comment]
The issue is not with the settings file - that was more of a blocker, I've tried having a local settings file inside my project without a relative path.

I've also tried running it with `meteor run --inspect --settings settings.json` and it does start (and then I press the green arrow). However breakpoints are never hit.

Perhaps there might be something deeper with meteor, given the number of issues referencing temporary/permanent sourcemapping issues.

Leaving this closed right now because I don't have any ideas/time on how to debug further.

**Comment by auchenberg** [comment]
@arlohosk I think you need to isolate the problem here. Try downloading https://github.com/auchenberg/meteor-simple-todos-react-custom-settings and see if it works on your computer. If it does, then we can conclude VS works with Meteor, and you probably should do a comparison between the project and yours to see what the difference is. Probably a dependency difference somewhere.

If the todo-project doesn't work on your machine, then I'd be happy to re-open this issue, and debug this further.
