### ISSUE TITLE
can't start Next: Node

### ISSUE THREAD

**Issue by eddyLazar** [Microsoft/vscode-recipes#68]
`Cannot find runtime 'next' on PATH. Make sure to have 'next' installed.`

when trying to start `Next: Node`

works fine with `Next: Chrome`

**Comment by auchenberg** [comment]
@eddyLazar Have you installed next.js, and is next available on your path inside your folder? https://github.com/zeit/next.js/

**Comment by auchenberg** [comment]
Closing due to now answer.
