### ISSUE TITLE
Debugging the Meteor API Node process not working

### ISSUE THREAD

**Issue by tab00** [Microsoft/vscode-recipes#70]
Visual Studio Code version: 1.19.3
Node version: 8.9.3
Meteor version: 1.6.1
Operating system: Windows 10

After pressing the green play button with "Meteor: Node" configuration, the Meteor app does not start. This error message later appears: `Cannot connect to runtime process, timeout after 30000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).`

The Debug console correctly shows:
```
Debugging with inspector protocol because a runtime executable is set.
C:\Program Files\nodejs\npm.cmd run debug
```

If I manually run the app by typing `meteor --inspect` and wait for the app to fully load, then press the play button, debugging appears to start working as the bottom status bar turns orange and the small debug control toolbar appears (pause, step over etc.), but they only stay for 10s, then it reverts back to the non-debugging mode and new lines appear in the terminal:
```
(STDERR) Debugger attached.
(STDERR) Debugger listening on ws://127.0.0.1:9229/426fde45-2b8f-4190-843a-90a6377d3a40
(STDERR) For help see https://nodejs.org/en/docs/inspector
```

The problem remains with other apps too, including a simple app via `meteor create test`.

How can this problem be fixed?

**Comment by ChuckIrvine** [comment]
I am seeing the same problem. It appears to be the same problem that I reported https://github.com/Microsoft/vscode-recipes/issues/58 and that @arlohosk reported https://github.com/Microsoft/vscode-recipes/issues/66.

**Comment by ChuckIrvine** [comment]
Hi Kenneth,

The very first thing I did before trying to get my own project working was to go through your instructions using the todo app. And, yes, everything went fine per the instructions in your recipe. 

I am at the latest version of Meteor with my project - 1.6.1. My experience is exactly the same as reported by @tab00. 

For my project by debug line is:

```
MONGO_URL="mongodb://<mongo url>/eversity" meteor run --port 4000 --inspect --settings settings-dev.json
```

I'm glad to help any way that I can, just let me know. Is there some way that I can trace something of interest?

Thanks, 
Chuck

**Comment by tab00** [comment]
> @tab00 Can I get you to try to pull down this project, https://github.com/auchenberg/meteor-simple-todos-react-custom-settings, and try the "Meteor: Node" configuration? You should see your Meteor app starting and the debugger attaching.

First this (and nothing more) appears in the debug console:
```
Debugging with inspector protocol because a runtime executable is set.
C:\Program Files\nodejs\npm.cmd run debug

```

Then an error notification appears at the top:
`Cannot connect to runtime process, timeout after 30000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9229).
`
I assume it's because the app wasn't started.

Just to check that `npm.cmd run debug` does work, I copied and pasted it into the terminal tab window and pressed enter, and the app started to run. So in the debug console it just looks as if `npm.cmd run debug` was typed in but the enter key was not pressed.

**Comment by auchenberg** [comment]
@tab00 @ChuckIrvine 

Okay, can you help me confirm a few things here, as I'm still a bit confused:

1. You both have pulled down https://github.com/auchenberg/meteor-simple-todos-react-custom-settings and successfully debugged the project from VS Code. Correct?

2. You both are trying to setup debugging with your own project, and this is there the problems occurs. Correct?

3. You are both running on Windows?

4. How long does your Meteor app take to boot? Longer than 30sec? In that case you could increase the `timeout` in your `launch.json`

Is it possible for any of you to upload a working project which we can debug together? I have Meteor working here in https://github.com/auchenberg/meteor-simple-todos-react-custom-settings, and can't reproduce the scenario.

**Comment by tab00** [comment]
> You both have pulled down https://github.com/auchenberg/meteor-simple-todos-react-custom-settings and successfully debugged the project from VS Code. Correct?
No, it didn't work as I had described just above.

> You are both running on Windows?
Yes, as written in the original post. Though I have done a clean re-installation of Windows recently since then.

**Comment by tab00** [comment]
![image](https://user-images.githubusercontent.com/12715448/36462959-3c927b3e-16f9-11e8-993c-4856d3669cb2.png)

**Comment by ChuckIrvine** [comment]
> You both have pulled down https://github.com/auchenberg/meteor-simple-todos-react-custom-settings and successfully debugged the project from VS Code. Correct?

Correct for me.

> You both are trying to setup debugging with your own project, and this is there the problems occurs. Correct?

Correct for me.

> You are both running on Windows?

No, I am running on the latest mac os.

> How long does your Meteor app take to boot? Longer than 30sec? In that case you could increase the timeout in your launch.json

The timeout doesn't matter for me. I can set it arbitrarily high and it still eventually times out.

> Is it possible for any of you to upload a working project which we can debug together? I have Meteor working here in https://github.com/auchenberg/meteor-simple-todos-react-custom-settings, and can't reproduce the scenario.

It sounds like @tab00 has a sample project that duplicates the problem. @tab00, if I am right can you make that project available?

**Comment by tab00** [comment]
> It sounds like @tab00 has a sample project that duplicates the problem. @tab00, if I am right can you make that project available?

Just run `meteor create test` and add `"debug": "meteor run --inspect"` to the `scripts` section in package.json. The result is the same - the app does not run when clicking on F5 or pressing the green play button, and debug times out.

**Comment by auchenberg** [comment]
Okay, sounds like we have two different issues here. Let's stick to @tab00's in this issue, so we can keep track of things in here, for us and for future people. 

Okay @tab00. Let's try to debug the sample project, so we can see if this is a windows specific problem.

1. Enable verbose logging by setting the `trace: "verbose"`, and set `"console": "integratedTerminal"` in your launch config so you have something like:

```
        {
            "type": "node",
            "request": "launch",
            "name": "Meteor: Node",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run", "debug"],
            "port": 9229,
            "timeout": 30000
            "trace": "verbose",
            "console": "integratedTerminal"
        }
```
2. Try start `Meteor: Node` You should now see VS Code switch to the integrated terminal when running `npm run dev`

3. What do you see in the integrated terminal? Does the meteor server start as expected? Copy paste the content of the terminal in here.

4. If you go to the debug console. At the top of the console you should see something like `/Verbose logs are written to:`.

5. Open that file and find the section from your recent session and attach it here (a gist would be great too)

The verbose log will tell os more on what's happening in your machine, and we will see if your `meteor` process get's started in debug mode, etc.


@ChuckIrvine You can try the same too with your project, but I'd love to have you creating new issue with as many details as possible, so we can keep this thread clean. It's already too mixed up with your two issues intertwined.

**Comment by tab00** [comment]
The verbose trace has helped in troubleshooting, as now I can see that apps do load, whereas before I saw no progress. Maybe `"trace": "verbose"` should be default. It appears that apps take longer than 30s to load for me (even a simple default one created from `meteor create test`), so I increased timeout to 120s, and the debugger successfully attaches. I've tried it in meteor-simple-todos-react-custom-settings as well as my own large app, and it's working, except breakpoints in startup code do not get hit, but that may be a different issue.

I think my clean re-installation of Windows and all software may have fixed the issue, as previously increasing timeout had no effect, and I thought I was experiencing the same problem as before.

So I think the problem has now been solved for me. Thank you for your assistance, @auchenberg.

**Comment by ChuckIrvine** [comment]
Hmmm. Well it's good that one of us got things working. I should have mentioned that I had discovered that the 30 second wasn't sufficient when I was trying to get the todo recipe to work. After increasing the timeout the recipe worked as advertised. Perhaps the recipe docs should be updated to a longer timeout. 

But things still don't work for my project. I'll try @auchenberg's debug instructions to see if they help me.

**Comment by ChuckIrvine** [comment]
Ok. Now I'm getting somewhere. In my terminal, when I invoke `Meteor: Node` I see:

```
~/src/meteor/radienz $ cd /Users/charlesirvine/src/meteor/radienz ; /usr/local/bin/npm run debug

> radienz@ debug /Users/charlesirvine/src/meteor/radienz
> MONGO_URL=<my mongo url> meteor  run --inspect --port 4000 --settings settings-development.json

[[[[[ ~/src/meteor/radienz ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While preparing to run:
   settings-development.json: file not found (settings file)

=> Your application has errors. Waiting for file change.
```
So the problem is that somehow my settings file isn't found. Trying to figure that out now.

**Comment by auchenberg** [comment]
@tab00 @ChuckIrvine Glad both of you got things working. Yay!

@tab00 We are considering changing the default, so process output is shown in the terminal. This would have made this much easier to discover. The verbose logging is and will be disabled by default, as the logs can become quite big.

For the breakpoints in your initial code, please see https://code.visualstudio.com/blogs/2017/12/20/chrome-debugging and try to enable `breakOnLoad`. This could help with breakpoints in your clientside code.
