### ISSUE TITLE
vue-cli recipe doesn't work

### ISSUE THREAD

**Issue by murphy55555** [Microsoft/vscode-recipes#71]
I followed this exactly and I cannot get vscode to break. I can see Chrome flash very briefly like it wants to break in vs code but it never does.

https://github.com/Microsoft/vscode-recipes/tree/master/vuejs-cli

My launch file:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "vuejs: chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}/src",
            "breakOnLoad": true,
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            }
        }
    ]
}

Snippet of my index.js in conf
    /**
     * Source Maps
     */

    productionSourceMap: true,
    // https://webpack.js.org/configuration/devtool/#production
    devtool: 'source-map',

**Comment by auchenberg** [comment]
@murphy55555 Can you provide some more details about your setup? Which version of the vue-cli are you using? Where are you trying to set breakpoints and what projet are you trying in? Public?

**Comment by murphy55555** [comment]
I'm following it through locally verbatim from your directions. Watch the video below to see versions and what I'm seeing. I paused it so you wouldn't have to wait for all of the packages to download. The Jing video capture also sometimes causes buttons and windows to be unclickable so you'll see me struggle a bit in the video. At the end of the day I get a flash that looks like the vscode debugger is going to stop but then it doesn't. Latest version of Chrome and the Chrome vscode extension. All other versions show up in video.

Hope this helps and appreciate your fast response earlier.
https://www.screencast.com/t/8XRa9ZP7U

**Comment by murphy55555** [comment]
I figured it out.
Instructions are the change devtool: 'source-map' in config/index.js
What I failed to notice is that this is in the file twice. One in the dev: export and another in the build: export. You must change the dev: export for it to work. The default value is devtool: 'cheap-module-eval-source-map'

**Comment by auchenberg** [comment]
@murphy55555 Ah, glad you worked it out. Let me update the recipe to make that more clear!
