### ISSUE TITLE
vue-cli recipe not working as intended

### ISSUE THREAD

**Issue by myandrienko** [Microsoft/vscode-recipes#74]
VSCode version: 1.20.0
vue-cli version: 2.9.3
Debugger for Chrome version: 4.1.0
Chrome version: 64.0.3282.140
OS: Windows 10 (10.0.16299 Build 16299)

Followed the recipe verbatim. Breakpoint is hit in `app.js` file generated by webpack, not in `HelloWorld.vue` file as intended.

![image](https://user-images.githubusercontent.com/975978/36100986-1bb45c2a-1019-11e8-99f3-8029d5d3e711.png)

**Comment by auchenberg** [comment]
Hi @myandrienko 

We have confirmed the issue. Stay tuned ;)

**Comment by auchenberg** [comment]
Closing this, as this is an upstream bug that needs to get fixed in vue-loader.

See https://github.com/vuejs/vue-loader/issues/1163
