### ISSUE TITLE
Vue recipe not working - stepping dives into minified code

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode-recipes#77]
https://github.com/Microsoft/vscode-recipes/blob/master/vuejs-cli/README.md

Despite following all the instructions, when I set a breakpoint and start stepping through code, I see `http://localhost:8080/app.js` open in a new tab (which has tens of thousands of lines). The `devtool` option is set to `'source-map'` for both dev and build. I also tried `'#source-map'` just to cover my bases, but that didn't work either.

`.vscode/launch.json` below:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Vue: Chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
  ]
}
```

**Comment by auchenberg** [comment]
Closing this, as this is an upstream bug that needs to get fixed in vue-loader, before we can do anything in VS Code. The recipe has a "notice" section in the top that warns about this. I wish we could do something

See https://github.com/vuejs/vue-loader/issues/1163

**Comment by ffxsam** [comment]
Ah, I missed that notice at the top. Thanks, I'll subscribe to the aforementioned issue to keep tabs on it.
