### ISSUE TITLE
Breakpoints lost after updating code

### ISSUE THREAD

**Issue by ChuckIrvine** [Microsoft/vscode-recipes#78]
Maybe it is just supposed to work this way.... Per the recipe if I am start client side meteor debugging and afterwards set breakpoints, the breakpoints are triggered as expected. However, if I update code then after that the previously set breakpoint are not triggered. I have to stop my client side debugging session and restart it to get the breakpoints to be active again.

Should it be working this way...?

**Comment by auchenberg** [comment]
This is expected if you change the code where the breakpoint is bound too.
