### ISSUE TITLE
Vue.js Debug: Some tweaks might be necessary.

### ISSUE THREAD

**Issue by uriannrima** [Microsoft/vscode-recipes#79]
Hello,

I've been looking for some ways to debug Vue.js Code, on Chrome or VSCode and found out this repository. I've managed to debug on VSCode, but was necessary to do a few tweaks:

1) Add "sourceMaps": true to the configuration.
2) Change devtools from 'source-map' to 'eval-source-map'.
3) Add "debugger" manually to where I wanted to debug, since the "transpiled" (I'm using babel-loader) file didn't seem to map accordingly when I added a breakpoint through the *.vue code, it was grayed out and didn't stop. Adding a debugger help to find the correct file (with a weird name, unfortunately),

Here are some info on my environment:

- vue-loader@13.7.1
- webpack@3.11.0
- web-dev-server@2.11.2
- vue-cli@2.9.3
- babel-core@6.26.0
- babel-loader@7.1.3

Used vue webpack template to create and build it.
And I doing something wrong, or the configuration might change on each case?

**Comment by auchenberg** [comment]
We have opened an issue on vue-cli explaining the problems we are seeing, which are rooted in invalid sourcemaps. See https://github.com/vuejs/vue-loader/issues/1163

In regards to your config, then the ` "sourceMaps"` property is enabled by default for our Chrome debugger, so setting this shouldn't have an influence, and we recommend `source-map` over `eval-source-map` for webpack as it contains more details which our debugger need. 

For now my recommendation would be to use the settings as per our recipe, https://github.com/Microsoft/vscode-recipes/tree/master/vuejs-cli, and use `debugger` statements when debugging in VS Code
