### ISSUE TITLE
[vuejs-cli] Mention userDataDir in the recipe

### ISSUE THREAD

**Issue by Zip753** [Microsoft/vscode-recipes#83]
Hi, thanks for your effort, I'm excited that I finally got debugging to work with Vue.js due to your recipe!

However, when setting up the `launch.json` config it didn't work at first and when I tried to launch the debugger it opened a blank tab in a new Chrome instance and VSCode debugger just hung up after waiting for 10 seconds. The fix was to add `userDataDir` field to the config, as described per this issue: https://github.com/Microsoft/vscode-chrome-debug/issues/111#issuecomment-225101947 After that everything worked as expected :sparkles:

Do you mind adding a notice in the recipe about this param? I usually have two browsers opened, one per each Chrome user/profile, therefore I suspect it might work for other users without specifying this option.

P.S. Just checked: if I have any instance of Chrome already opened, it hangs as described above, otherwise it launches successfully with one of my user profiles.

**Comment by auchenberg** [comment]
@Zip753 What version of Chrome debugger are you using? 

@roblourens I'm wondering if this is a new Chrome bug?

**Comment by Zip753** [comment]
@auchenberg the version of Chrome (and debugger as well?) is the following, as per `chrome://settings/help`:
`Version 64.0.3282.186 (Official Build) (64-bit)`

**Comment by auchenberg** [comment]
@Zip753 Yes the version of the Chrome debugger as well would be great. Thanks!

**Comment by Zip753** [comment]
@auchenberg Could you please suggest a way to check that? I can't figure it out 😬

**Comment by auchenberg** [comment]
You can go to the Extensions section from within VS Code, and see the version in the installed list

![launch json timey-client 2018-03-05 14-25-52](https://user-images.githubusercontent.com/173559/37003218-2c8a86b4-2081-11e8-98ae-eb06f946aa5f.png)

**Comment by Zip753** [comment]
Ah, sorry, you meant the VSCode extension version... It's `4.0.0` (I've disabled the auto-update some time ago due to the bug in upstream version of another extension).

**Comment by Zip753** [comment]
Updated to `4.1.0` - the same issue takes place.

**Comment by roblourens** [comment]
Can you set `"trace": true`, run again without the userDataDir, and upload the log here?

It now should set a userDataDir automatically by default, unless you have set it to null, so I don't know why this would happen.

**Comment by Zip753** [comment]
@roblourens here's the gist with the logs and `launch.json` config for reference: https://gist.github.com/Zip753/7fee7f9439bad9ed8789dafca3605f2a

**Comment by roblourens** [comment]
Oh, you have a runtimeExecutable set, and it doesn't add the userDataDir automatically in that case. Because you might be launching some app or script that doesn't want that parameter.

**Comment by Zip753** [comment]
@roblourens found the notice in the documentation:
> Chrome user profile note: Normally, if Chrome is already running when you start debugging with a launch config, then the new instance won't start in remote debugging mode. So by default, the extension launches Chrome with a separate user profile in a temp folder, (unless you are using the runtimeExecutable field). Use the userDataDir launch config field to override or disable this.

OK, case closed then, since it's probably not related to `vuejs-cli` recipe specifically in any way :man_shrugging:
