### ISSUE TITLE
debugger is not hitting

### ISSUE THREAD

**Issue by roopkt** [Microsoft/vscode-recipes#87]
Hi I am using Vscode 

```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:47:13.351Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```
and  Node
```
v8.6.0
```

Jest version
```
v20.0.4
```
Operating System
```
Windows 2010
```
When I debug using current or all debugger is not hitting. Which version you expect should work ?

**Comment by FishOrBear** [comment]
@roopkt  @auchenberg 

I think he meant to add breakpoints in the editor but it did not hit.

I also encountered the same problem, I use the following code to hit the breakpoint.

```js
test('d', () =>
{
    debugger
    console.log("hello");
});
```

**Comment by FishOrBear** [comment]
Update, the latest version 1.22.1, has been able to normally trigger breakpoints.

**Comment by auchenberg** [comment]
@FishOrBear Good to hear. Closing this until we hear anything from OP.
