### ISSUE TITLE
tsc-watch not terminating after debug

### ISSUE THREAD

**Issue by ldiego08** [Microsoft/vscode-recipes#92]
I was able to get the [Docker-Typescript](https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript) recipe running, however the `tsc-watch` task doesn't terminate after detaching from the docker container. Is there another task I can use to terminate it? i.e as a `postDebugTask`?

**Comment by devuxer** [comment]
Wondering the exact same thing.

**Comment by auchenberg** [comment]
Yes we support postDebugTasks. See https://code.visualstudio.com/docs/editor/debugging
