### ISSUE TITLE
Please update config settings for Vue CLI >= 3

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode-recipes#96]

**Comment by auchenberg** [comment]
@eladcandroid If you can provide some more details for the community to know what the ask is, or even contribute with a PR with would be much appreciated.

**Comment by eladcandroid** [comment]
@auchenberg 
I'm talking about this section:
https://github.com/Microsoft/vscode-recipes/tree/master/vuejs-cli#update-your-webpack-configuration

The webpack customized configuration in Vue CLI 3 is now placed in **vue.config.js** file:

```javascript
module.exports = {
 ....
  configureWebpack: {
    devtool: 'sourcemap'
  }
};
```

(As described here: https://github.com/vuejs/vue-cli/blob/dev/docs/config.md)

Please correct me if i'm wrong. I'm not sure about the PR already.

**Comment by tvkit** [comment]
FWIW, this is now [documented](https://vuejs.org/v2/cookbook/debugging-in-vscode.html) at vuejs.org.

**Comment by eladcandroid** [comment]
@tvkit I know. I'm talking about Microsoft docs...

**Comment by auchenberg** [comment]
@eladcandroid Where do you see Vuejs + VS Code debugging on docs.com?

**Comment by tvkit** [comment]
@eladcandroid  Correct, it should be updated.  

@auchenberg  See this  link: https://vuejs.org/v2/cookbook/debugging-in-vscode.html
