### ISSUE TITLE
Meteor auto-attach to client or wtv

### ISSUE THREAD

**Issue by janat08** [Microsoft/vscode-recipes#98]
https://github.com/Microsoft/vscode/issues/40917

**Comment by auchenberg** [comment]
@janat08 I'm not sure what you are opening an issue for here?

**Comment by janat08** [comment]
Don't know, but I guess I failed at auto-attaching to chrome using one of the recipes for meteor.

**Comment by janat08** [comment]
Would you update the recipe?

**Comment by janat08** [comment]
I think the issue was with me expecting that editing shortcut for startmenu expecting it to be the one on taskbar on win 10 would hold.
