### ISSUE TITLE
Meteor server debug fails

### ISSUE THREAD

**Issue by janat08** [Microsoft/vscode-recipes#99]
Using the recipe I timout with ECONNREFUSED 127.0.0.1.9229.

**Comment by Hereward** [comment]
Same for me.

**Comment by janat08** [comment]
update plz?

**Comment by russ-northrup** [comment]
Specifically, from PowerShell:

meteor update --patch
meteor install --save @babel/runtime
meteor install --save bcrypt

**Comment by janat08** [comment]
So the recipe actually worked for you thereafter?

**Comment by russ-northrup** [comment]
No such luck... But it does not throw that error.

Now there are no errors; I can connect a browser to it and see a correctly titled window with the correct background, but no data on the screen.

Still troubleshooting.

**Comment by derwaldgeist** [comment]
The Meteor recipe won't work for me either on macOS. I only get the connection refused error message. If I start npm run debug on the command line, everything works fine.

**Comment by mrslwiseman** [comment]
I've had exact same problem all week and I've been trying hard to get it going. I finally succeeded with server side debugging, havn't quite worked out server/client at same time, but Im happy.
Try this

1.  launch.json:
```{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "server",
            "restart": true,
            "port": 9229,
        },
    ],
}
```

2. run meteor in its own terminal
`meteor run --inspect`

3. Start up vscode debugger.
Take note of `debugger attached` output in meteors terminal

4. Open up browser `localhost:3000` and go for it!

For client side as well:
5. Chrome devtools > Sources: Add your work directory, then add client breakpoints there.

Has worked flawlessly for me so far.
